"""Generates the Reevz Habitz launcher icon: a raised fist, for victory.

Run from anywhere:  python tools/make_icon.py [preview.png]

Writes the adaptive-icon layers to app/src/main/res/drawable:
  ic_launcher_background.xml  - solid colour
  ic_launcher_foreground.xml  - the fist
  ic_launcher_monochrome.xml  - the same fist, for Android 13+ themed icons

The fist is built from rounded rectangles separated by real gaps rather than drawn outlines, so
the monochrome layer (which only keeps the shape's alpha) still shows the fingers and thumb.
minSdk is 26, so every supported device uses the adaptive icon and no PNG mipmaps are needed.

Pass a path to also render a preview through a circular launcher mask (needs Pillow).
"""
import os
import sys

RES = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "app", "src", "main", "res", "drawable")

BACKGROUND = "#1A1B26"  # Tokyo Night background
FIST = "#F5B93B"        # victory gold

# Shapes on the 108x108 adaptive-icon canvas: (left, top, right, bottom, corner radius).
# Only the centre ~66x66 is guaranteed visible under every launcher mask; the forearm runs on
# past it to the bottom edge, so the fist reads as raised from below.
SHAPES = [
    # Four curled fingers seen from the front, knuckles arched: middle finger highest.
    (31, 31, 41, 52, 5),
    (43, 27, 53, 52, 5),
    (55, 28, 65, 52, 5),
    (67, 32, 77, 52, 5),
    # Thumb folded across the lower finger segments.
    (28, 55, 62, 65, 5),
    # Back of the hand: beside the thumb's tip, and below the thumb.
    (65, 55, 77, 76, 4),
    (30, 68, 77, 80, 6),
    # Wrist and forearm.
    (38, 78, 70, 108, 0),
]


def rounded_rect_path(left, top, right, bottom, r):
    if r == 0:
        return f"M{left},{top}H{right}V{bottom}H{left}Z"
    return (
        f"M{left + r},{top}H{right - r}"
        f"A{r},{r} 0 0 1 {right},{top + r}V{bottom - r}"
        f"A{r},{r} 0 0 1 {right - r},{bottom}H{left + r}"
        f"A{r},{r} 0 0 1 {left},{bottom - r}V{top + r}"
        f"A{r},{r} 0 0 1 {left + r},{top}Z"
    )


def vector(paths_xml):
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by tools/make_icon.py. Edit the script, not this file. -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="108dp"\n'
        '    android:height="108dp"\n'
        '    android:viewportWidth="108"\n'
        '    android:viewportHeight="108">\n'
        f"{paths_xml}"
        "</vector>\n"
    )


def fist_xml(color):
    data = "".join(rounded_rect_path(*shape) for shape in SHAPES)
    return f'    <path\n        android:fillColor="{color}"\n        android:pathData="{data}" />\n'


def write(name, content):
    with open(os.path.join(RES, name), "w", encoding="utf-8", newline="\n") as out:
        out.write(content)


def preview(path, size=432):
    from PIL import Image, ImageDraw

    scale = size / 108
    image = Image.new("RGBA", (size, size), BACKGROUND)
    draw = ImageDraw.Draw(image)
    for left, top, right, bottom, r in SHAPES:
        draw.rounded_rectangle(
            [left * scale, top * scale, right * scale - 1, bottom * scale - 1],
            radius=r * scale,
            fill=FIST,
        )
    # Launchers show the central 72dp of the 108dp canvas, masked to their shape.
    inset = 18 * scale
    visible = image.crop((inset, inset, size - inset, size - inset))
    mask = Image.new("L", visible.size, 0)
    ImageDraw.Draw(mask).ellipse([0, 0, visible.size[0] - 1, visible.size[1] - 1], fill=255)
    out = Image.new("RGBA", visible.size, (255, 255, 255, 0))
    out.paste(visible, (0, 0), mask)
    out.save(path)


def main():
    write(
        "ic_launcher_background.xml",
        vector(f'    <path\n        android:fillColor="{BACKGROUND}"\n        android:pathData="M0,0h108v108h-108z" />\n'),
    )
    write("ic_launcher_foreground.xml", vector(fist_xml(FIST)))
    # Themed icons take only the alpha; the system supplies the colour.
    write("ic_launcher_monochrome.xml", vector(fist_xml("#FFFFFFFF")))
    print("Wrote launcher icon layers to", os.path.normpath(RES))
    if len(sys.argv) > 1:
        preview(sys.argv[1])
        print("Preview:", sys.argv[1])


if __name__ == "__main__":
    main()
